### PR TITLE
Add notes on Windows support, reshuffle download links

### PR DESCRIPTION
**Pull request by micolous**
I've added some notes on using `mosh` on Windows, as there is a common misconception that mosh does not work at all on Windows, and this creates a lot of noise (see mobile-shell/mosh#293).  Instead, these users should be directed to the Chrome version of mosh, because this is the easiest to install.

I have noted that pointing to the Chrome version of mosh for Windows users is _intentional_.

If I recall correctly, the Cygwin version had some strange terminal limitations.

In the process I noticed some of the rows for download links had overflowed, and I took the opportunity to reorder them into logical groups.

### CODE REVIEW

**Comment by cgull** [comment]
Cygwin is more difficult to use, but there's still some reasons to use it.  See #36.  I think that goes nicely with your Windows instructions.
I think moving the common client platforms (OS X, Windows, Chrome, Android) to the top of the install instructions makes some sense, but that de-emphasizes Linux's status as the first-class platform.  Opinions?

**Comment by keithw** [comment]
(I don't have a strong opinion here on where to put Linux vs. the other ones.)

**Comment by micolous** [comment]
The additions in #37 look good to me.  I knew there was something to it, it's just been a long while since I ran the Cygwin version.

As for rearranging, while I see your point about emphasising platforms without package managers or without packages called "mosh" (though arguably Chrome's is "discoverable"), I am concerned about emphasising platforms without support for both the client and the server.

Ta!

**Comment by timofonic** [comment]
Sorry, but I don't consider my comments as "noise". I'm less skilled and probably not explained correctly  with my broken English, but I try to think about this issue because it makes to manage my machines a lot more difficult. 

I consider that requiring to use a web browser just to connect to a remote shell seems insane. Anyway, these days we love to warm everywhere by wasting CPU and using a web browser plus tons of overbloated stuff just to run a text editor (Atom, for example).

I want MOSH, but I'm unable to see a sane way to have it everywhere with an Open Source client.

I also commented in the issue tracker.

**Pull request merged**
