### PR TITLE
Added AES-128 vs AES-192/AES-256 discussion to the FAQ.

### PR DESCRIPTION
**Pull request by javabrett**
Fixed mobile-shell/mosh#993.

### CODE REVIEW

**Comment by javabrett** [comment]
A month in, so bumping this to see if it needs review or changed, or close if not wanted. /cc @eminence

**Comment by javabrett** [comment]
Rebased/resolved, bump.

**Comment by javabrett** [comment]
Any path or suggestions to get this reviewed?

**Comment by keithw** [comment]
@eminence Do you have cycles to take a look at this?

**Comment by eminence** [comment]
@keithw Should I leave it to you to deploy these changes to mosh.org?   If you want, find me on IRC (or email) if you want to walk me through the process of deploying this live.

**Comment by javabrett** [comment]
@eminence Is deployment to mosh.org pulled from the git repo here?  If so, I think this PR will need to be merged before deployment can occur.

Thanks.

**Comment by keithw** [comment]
Merged and deployed. Thanks, @eminence and @javabrett !

**Pull request merged**
